// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://argaeubfqfyddtnsorwc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFyZ2FldWJmcWZ5ZGR0bnNvcndjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTk0MzA5MzAsImV4cCI6MjA3NTAwNjkzMH0.DF9cQ9juHRkKbWFcbbehdijDrD4WBnlBUZGP2RlQIfU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});